config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'login' => 'pages#login'
  get 'contact' => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def login
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Web App</a>
    </div>
    <div class="collapse navbar-collapse navbar-right" id="myNav">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home<span class="sr-only">(current)</span></a></li>
        <li><a href="<%= login_path %>">Login</a></li>
        <li><a href="<%= contact_path %>">Contact</a></li>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Web App</h1>
  <p>This will be slider position.</p>
</div>
<div class="row">
	  <div class="col-md-4">

	  </div>
	  <div class="col-md-4">

	  </div>
	  <div class="col-md-4">

	  </div>
</div>

app/views/pages/login.html.erb
<div class="row">
  <div class="col-md-5">
  </div>
  <div class="col-md-2">
  		<form>
		  <div class="form-group">
		    <label for="exampleInputEmail1">Email address</label>
		    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
		  </div>
		  <div class="form-group">
		    <label for="exampleInputPassword1">Password</label>
		    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
		  </div>
		  <a href="#">Register Now</a> | <a href="#">Forgot Password?</a>
		  <button type="submit" class="btn btn-default">Submit</button>
	</form>
  </div>
  <div class="col-md-5"></div>
</div>